// Mapping noms d'équipes anglais → français
const EN_TO_FR = {
  // Amérique du Nord
  'United States':          'États-Unis',
  'USA':                    'États-Unis',
  'Canada':                 'Canada',
  'Mexico':                 'Mexique',
  'Panama':                 'Panama',
  'Jamaica':                'Jamaïque',
  'Costa Rica':             'Costa Rica',
  'Honduras':               'Honduras',
  'Guatemala':              'Guatemala',
  'El Salvador':            'Salvador',
  'Haiti':                  'Haïti',
  'Cuba':                   'Cuba',
  'Trinidad and Tobago':    'Trinité-et-Tobago',
  'Curaçao':               'Curaçao',
  // Amérique du Sud
  'Brazil':                 'Brésil',
  'Argentina':              'Argentine',
  'Uruguay':                'Uruguay',
  'Colombia':               'Colombie',
  'Ecuador':                'Équateur',
  'Chile':                  'Chili',
  'Paraguay':               'Paraguay',
  'Peru':                   'Pérou',
  'Venezuela':              'Venezuela',
  'Bolivia':                'Bolivie',
  'Guyana':                 'Guyane',
  'Suriname':               'Surinam',
  // Europe
  'France':                 'France',
  'Germany':                'Allemagne',
  'Spain':                  'Espagne',
  'England':                'Angleterre',
  'Portugal':               'Portugal',
  'Netherlands':            'Pays-Bas',
  'Belgium':                'Belgique',
  'Italy':                  'Italie',
  'Croatia':                'Croatie',
  'Poland':                 'Pologne',
  'Switzerland':            'Suisse',
  'Serbia':                 'Serbie',
  'Denmark':                'Danemark',
  'Austria':                'Autriche',
  'Turkey':                 'Turquie',
  'Scotland':               'Écosse',
  'Wales':                  'Pays de Galles',
  'Norway':                 'Norvège',
  'Sweden':                 'Suède',
  'Czech Republic':         'Tchéquie',
  'Czechia':                'Tchéquie',
  'Slovakia':               'Slovaquie',
  'Hungary':                'Hongrie',
  'Romania':                'Roumanie',
  'Greece':                 'Grèce',
  'Albania':                'Albanie',
  'Slovenia':               'Slovénie',
  'Finland':                'Finlande',
  'Iceland':                'Islande',
  'Ireland':                'Irlande',
  'Northern Ireland':       'Irlande du Nord',
  'Ukraine':                'Ukraine',
  'Georgia':                'Géorgie',
  'Kosovo':                 'Kosovo',
  'Bosnia and Herzegovina': 'Bosnie-Herzégovine',
  'Bosnia':                 'Bosnie',
  'Montenegro':             'Monténégro',
  'Luxembourg':             'Luxembourg',
  'North Macedonia':        'Macédoine du Nord',
  'Armenia':                'Arménie',
  'Belarus':                'Biélorussie',
  'Azerbaijan':             'Azerbaïdjan',
  // Afrique
  'Morocco':                'Maroc',
  'Senegal':                'Sénégal',
  'Nigeria':                'Nigeria',
  'Cameroon':               'Cameroun',
  'Egypt':                  'Égypte',
  "Ivory Coast":            "Côte d'Ivoire",
  "Cote d'Ivoire":          "Côte d'Ivoire",
  'Ghana':                  'Ghana',
  'Tunisia':                'Tunisie',
  'Algeria':                'Algérie',
  'Mali':                   'Mali',
  'South Africa':           'Afrique du Sud',
  'DR Congo':               'RD Congo',
  'Democratic Republic of Congo': 'RD Congo',
  'Congo DR':               'RD Congo',
  'Zambia':                 'Zambie',
  'Zimbabwe':               'Zimbabwe',
  'Angola':                 'Angola',
  'Mozambique':             'Mozambique',
  'Uganda':                 'Ouganda',
  'Kenya':                  'Kenya',
  'Ethiopia':               'Éthiopie',
  'Cabo Verde':             'Cap-Vert',
  'Cape Verde':             'Cap-Vert',
  'Gabon':                  'Gabon',
  'Burkina Faso':           'Burkina Faso',
  'Guinea':                 'Guinée',
  'Equatorial Guinea':      'Guinée équatoriale',
  'Guinea-Bissau':          'Guinée-Bissau',
  'Benin':                  'Bénin',
  'Togo':                   'Togo',
  'Namibia':                'Namibie',
  'Mauritania':             'Mauritanie',
  'Niger':                  'Niger',
  'Tanzania':               'Tanzanie',
  'Liberia':                'Liberia',
  'Sierra Leone':           'Sierra Leone',
  'Central African Republic': 'Rép. centrafricaine',
  'Sudan':                  'Soudan',
  // Asie
  'Japan':                  'Japon',
  'South Korea':            'Corée du Sud',
  'Korea Republic':         'Corée du Sud',
  'Iran':                   'Iran',
  'Saudi Arabia':           'Arabie saoudite',
  'Australia':              'Australie',
  'Qatar':                  'Qatar',
  'Uzbekistan':             'Ouzbékistan',
  'Iraq':                   'Irak',
  'Jordan':                 'Jordanie',
  'United Arab Emirates':   'Émirats arabes unis',
  'UAE':                    'Émirats arabes unis',
  'China':                  'Chine',
  'China PR':               'Chine',
  'Thailand':               'Thaïlande',
  'Vietnam':                'Viêt Nam',
  'Indonesia':              'Indonésie',
  'Malaysia':               'Malaisie',
  'Bahrain':                'Bahreïn',
  'Kuwait':                 'Koweït',
  'Oman':                   'Oman',
  'Syria':                  'Syrie',
  'Lebanon':                'Liban',
  'Palestine':              'Palestine',
  'Tajikistan':             'Tadjikistan',
  'Kyrgyzstan':             'Kirghizstan',
  'Turkmenistan':           'Turkménistan',
  'Kazakhstan':             'Kazakhstan',
  'India':                  'Inde',
  'Philippines':            'Philippines',
  'Singapore':              'Singapour',
  // Océanie
  'New Zealand':            'Nouvelle-Zélande',
  'Fiji':                   'Fidji',
  'Papua New Guinea':       'Papouasie-Nv-Guinée',
  'Solomon Islands':        'Îles Salomon',
  'Vanuatu':                'Vanuatu',
};

/**
 * Retourne le nom de l'équipe dans la langue souhaitée.
 * Si lang !== 'fr' ou si aucune traduction n'existe, retourne le nom d'origine.
 */
export const teamName = (name, lang) => {
  if (!name) return '';
  if (lang !== 'fr') return name;
  return EN_TO_FR[name] ?? name;
};
